kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-cluster-access
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/eviction"
      - "nodes"
    verbs:
      - "create"
      - "list"
      - "patch"
      - "delete"
      - "deletecollection"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "deployments/scale"
      - "replicasets"
    verbs:
      - "delete"
      - "deletecollection"
      - "list"
      - "patch"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "list"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - "deletecollection"
      - "get"
      - "patch"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "patch"
  - apiGroups:
      - "rook.io"
    resources:
      - "volumes"
    verbs:
      - "list"
      - "patch"
  - apiGroups:
      - "ceph.rook.io"
    resources:
      - "cephclusters"
    verbs:
      - "get"
      - "patch"
